# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161217_0819'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filemetaobject',
            unique_together=set([('name', 'parent')]),
        ),
    ]
